### ISSUE TITLE
security:profile-list -> No IsSsoEnabled field on Profile 

### ISSUE THREAD

**Issue by vaumont** [anandbn/security-sfdx-utils#1]
$ sfdx security:profile-list  -u so
ERROR running security:profile-list:  
select Description,Id,IsSsoEnabled,Name,UserType from
                      ^
ERROR at Row:1:Column:23
No such column 'IsSsoEnabled' on entity 'Profile'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

**Comment by anandbn** [comment]
Fixed in https://github.com/anandbn/security-sfdx-utils/commit/eedef7d45bbe8205cd470cab673d2cc1bdf75308
